import Head from 'next/head';
import Link from 'next/link';

import Navbar from './Navbar';

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>Samuel Ping | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div>{children}</div>

      <Link href="/">
        <footer>Return to home</footer>
      </Link>
    </>
  );
}
