# Builds and pushes frontend to gh-pages branch
# Pushes backend to server branch

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pushes frontend code to gh-pages branch
  client-integration:
    name: integrate-client
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # building the website
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_MATOMO_URL=$NEXT_PUBLIC_MATOMO_URL" > .env.local
          echo "NEXT_PUBLIC_MATOMO_SITE_ID=$NEXT_PUBLIC_MATOMO_SITE_ID" >> .env.local
        env:
          NEXT_PUBLIC_MATOMO_URL: ${{ secrets.NEXT_PUBLIC_MATOMO_URL }}
          NEXT_PUBLIC_MATOMO_SITE_ID: ${{ secrets.NEXT_PUBLIC_MATOMO_SITE_ID }}
        working-directory: ./client
      - name: build site
        run: |
          npm ci
          npm run export
          touch out/.nojekyll
          echo "samuelping.me" > out/CNAME
          echo "# Hi!" > out/README.md
          echo "You're currently looking at the build artifacts of my website. To check out the code, switch over to the [Main branch](https://github.com/samuel-ping/personal-website-v3)!" >> out/README.md
          echo "#### Note - This message was automatically generated." >> out/README.md
        working-directory: ./client

      # push build artifacts to gh-pages branch
      - name: deploy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./client/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # pushes backend code to server branch
  server-integration:
    name: server-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: deploy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: server
          FOLDER: ./server
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
