# Builds and pushes frontend to gh-pages branch
# Pushes backend to server branch

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pushes frontend code to gh-pages branch
  client-integration:
    name: integrate-client
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # building the website
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: build site
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll
          echo "# Hi!" > out/README.md
          echo "You're currently looking at the build artifacts of my website. To check out the code, switch over to my [personal-website repository!](https://github.com/samuel-ping/personal-website)!" >> out/README.md
          echo "#### Note - This message was automatically generated." >> out/README.md
        working-directory: ./

      - name: push build artifacts to samuel-ping.github.io
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:samuel-ping/samuel-ping.github.io.git
          BRANCH: gh-pages
          FOLDER: ./out
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}